modLoader="javafml"
loaderVersion="[43,)"
license="All rights reserved"
issueTrackerURL="https://github.com/Wehavecookies56/Kingdom-Keys/issues"
[[mods]]
modId="kingdomkeys"
version="${file.jarVersion}"
displayName="Kingdom Keys"
displayURL="https://www.curseforge.com/minecraft/mc-mods/kingdom-keys-re-coded"
credits="Remorse Code, Collecter, EthanGold, Sr.Gato and Lewis Weekes for supporting the mod on Patreon! Square Enix for Kingdom Hearts"
authors="Wehavecookies56, Abelatox, Wynd, stel1034"
description='''
A mod inspired by Kingdom Hearts adding various elements from the games.
'''
[[dependencies.kingdomkeys]]
    modId="jei"
    mandatory=false
    versionRange="[9.7,)"
    ordering="BEFORE"
    side="BOTH"
[[dependencies.kingdomkeys]]
    modId="epicfight"
    mandatory=false
    versionRange="[20.9,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.kingdomkeys]]
    modId="magicksaddon"
    mandatory=false
    versionRange="[1.20.1-0.7.5,)"
    ordering="BEFORE"
    side="BOTH"
